// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Subchron.API.Data;

#nullable disable

namespace Subchron.API.Migrations;

[DbContext(typeof(SubchronDbContext))]
[Migration("20260504120000_AddIdleLockFields")]
public partial class AddIdleLockFields : Migration
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0");

        modelBuilder.Entity("Subchron.API.Models.Entities.User", b =>
        {
            b.Property<int>("UserID")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

            b.Property<string>("AvatarUrl")
                .HasMaxLength(500)
                .HasColumnType("nvarchar(500)");

            b.Property<DateTime>("CreatedAt")
                .ValueGeneratedOnAdd()
                .HasColumnType("datetime2")
                .HasDefaultValueSql("SYSUTCDATETIME()");

            b.Property<string>("Email")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("nvarchar(256)");

            b.Property<bool>("EmailVerified")
                .ValueGeneratedOnAdd()
                .HasColumnType("bit")
                .HasDefaultValue(false);

            b.Property<string>("ExternalId")
                .HasMaxLength(128)
                .HasColumnType("nvarchar(128)");

            b.Property<string>("ExternalProvider")
                .HasMaxLength(20)
                .HasColumnType("nvarchar(20)");

            b.Property<bool>("IdleLockEnabled")
                .ValueGeneratedOnAdd()
                .HasColumnType("bit")
                .HasDefaultValue(false);

            b.Property<bool>("IdleLockIsLocked")
                .ValueGeneratedOnAdd()
                .HasColumnType("bit")
                .HasDefaultValue(false);

            b.Property<DateTime?>("IdleLockLastSeenAt")
                .HasColumnType("datetime2");

            b.Property<DateTime?>("IdleLockLockedAt")
                .HasColumnType("datetime2");

            b.Property<int>("IdleLockPinFailedCount")
                .ValueGeneratedOnAdd()
                .HasColumnType("int")
                .HasDefaultValue(0);

            b.Property<string>("IdleLockPinHash")
                .HasMaxLength(255)
                .HasColumnType("nvarchar(255)");

            b.Property<DateTime?>("IdleLockPinLockoutUntil")
                .HasColumnType("datetime2");

            b.Property<DateTime?>("IdleLockPinSetAt")
                .HasColumnType("datetime2");

            b.Property<int?>("IdleLockTimeoutMinutes")
                .HasColumnType("int");

            b.Property<bool>("IsActive")
                .ValueGeneratedOnAdd()
                .HasColumnType("bit")
                .HasDefaultValue(true);

            b.Property<DateTime?>("LastLoginAt")
                .HasColumnType("datetime2");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("nvarchar(100)");

            b.Property<int?>("OrgID")
                .HasColumnType("int");

            b.Property<string>("Password")
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnType("nvarchar(255)");

            b.Property<string>("RecoveryCodesHash")
                .HasColumnType("NVARCHAR(MAX)");

            b.Property<int>("Role")
                .HasColumnType("int");

            b.Property<bool>("TotpEnabled")
                .ValueGeneratedOnAdd()
                .HasColumnType("bit")
                .HasDefaultValue(false);

            b.Property<byte[]>("TotpSecret")
                .HasColumnType("varbinary(64)");

            b.HasKey("UserID");

            b.HasIndex("Email")
                .IsUnique();

            b.HasIndex("OrgID");

            b.HasIndex("ExternalProvider", "ExternalId")
                .IsUnique()
                .HasFilter("[ExternalProvider] IS NOT NULL AND [ExternalId] IS NOT NULL");

            b.ToTable("Users", null, t =>
            {
                t.HasCheckConstraint("CK_Users_Role_Valid", "[Role] IN (1,2,3,4,5,6,7)");
            });
        });
    }
}
