// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Subchron.API.Data;

#nullable disable

namespace Subchron.API.MigrationsTenant
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260309155230_OrgShiftTables")]
    partial class OrgShiftTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Subchron.API.Models.Entities.AttendanceCorrection", b =>
                {
                    b.Property<int>("CorrectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CorrectionID"));

                    b.Property<int>("AttendanceID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("OrgID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProposedTimeIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProposedTimeOut")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reasons")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RequestedByUserID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CorrectionID");

                    b.HasIndex("AttendanceID");

                    b.HasIndex("OrgID");

                    b.HasIndex("RequestedByUserID");

                    b.ToTable("AttendanceCorrections", (string)null);
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.AttendanceLog", b =>
                {
                    b.Property<int>("AttendanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceID"));

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("EmpID")
                        .HasColumnType("int");

                    b.Property<decimal?>("GeoLat")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("GeoLong")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("GeoStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date");

                    b.Property<string>("MethodIn")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MethodOut")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("OrgID")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("TimeIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeOut")
                        .HasColumnType("datetime2");

                    b.HasKey("AttendanceID");

                    b.HasIndex("EmpID");

                    b.HasIndex("LogDate");

                    b.HasIndex("OrgID");

                    b.ToTable("AttendanceLogs", (string)null);
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.Department", b =>
                {
                    b.Property<int>("DepID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("OrgID")
                        .HasColumnType("int");

                    b.HasKey("DepID");

                    b.HasIndex("OrgID");

                    b.HasIndex("OrgID", "DepartmentName")
                        .IsUnique();

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.Employee", b =>
                {
                    b.Property<int>("EmpID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpID"));

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ArchivedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ArchivedReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("AttendanceQrIssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AttendanceQrToken")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("City")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateHired")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("EmergencyContactRelation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("EmpNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("IdPictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("OrgID")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PhoneNormalized")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RestoreReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("RestoredAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RestoredByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("SignatureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StateProvince")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("WorkState")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("EmpID");

                    b.HasIndex("AttendanceQrToken")
                        .IsUnique()
                        .HasFilter("[AttendanceQrToken] IS NOT NULL");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("OrgID");

                    b.HasIndex("UserID");

                    b.HasIndex("OrgID", "Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL AND [Email] != ''");

                    b.HasIndex("OrgID", "EmpNumber")
                        .IsUnique();

                    b.HasIndex("OrgID", "PhoneNormalized")
                        .IsUnique()
                        .HasFilter("[PhoneNormalized] IS NOT NULL AND [PhoneNormalized] != ''");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.ExportJob", b =>
                {
                    b.Property<int>("ExportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExportID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("date");

                    b.Property<string>("ExportType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ExportedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("OrgID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ExportID");

                    b.HasIndex("ExportedByUserID");

                    b.HasIndex("OrgID");

                    b.ToTable("ExportJobs", (string)null);
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.LeaveRequest", b =>
                {
                    b.Property<int>("LeaveRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveRequestID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("EmpID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("OrgID")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedByUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("LeaveRequestID");

                    b.HasIndex("EmpID");

                    b.HasIndex("OrgID");

                    b.HasIndex("StartDate");

                    b.HasIndex("Status");

                    b.ToTable("LeaveRequests", (string)null);
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.LeaveType", b =>
                {
                    b.Property<int>("LeaveTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveTypeID"));

                    b.Property<int>("AccrualType")
                        .HasColumnType("int");

                    b.Property<bool>("AllowNegativeBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("AppliesTo")
                        .HasColumnType("int");

                    b.Property<int?>("CarryOverMaxDays")
                        .HasColumnType("int");

                    b.Property<int>("CarryOverType")
                        .HasColumnType("int");

                    b.Property<decimal>("DefaultDaysPerYear")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LeaveTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrgID")
                        .HasColumnType("int");

                    b.Property<bool>("RequireApproval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("RequireDocument")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("LeaveTypeID");

                    b.HasIndex("OrgID");

                    b.ToTable("LeaveTypes", (string)null);
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.Location", b =>
                {
                    b.Property<int>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationID"));

                    b.Property<string>("DeactivationReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("GeoLat")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("GeoLong")
                        .HasColumnType("decimal(9,6)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrgID")
                        .HasColumnType("int");

                    b.Property<string>("PinColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("blue");

                    b.Property<int>("RadiusMeters")
                        .HasColumnType("int");

                    b.HasKey("LocationID");

                    b.HasIndex("OrgID");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.OrgAttendanceConfig", b =>
                {
                    b.Property<int>("OrgID")
                        .HasColumnType("int");

                    b.Property<bool>("AllowManualEntry")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoClockOutEnabled")
                        .HasColumnType("bit");

                    b.Property<decimal?>("AutoClockOutMaxHours")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DefaultShiftTemplateCode")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("EnforceGeofence")
                        .HasColumnType("bit");

                    b.Property<bool>("PreventDoubleClockIn")
                        .HasColumnType("bit");

                    b.Property<string>("PrimaryMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("RequireGeo")
                        .HasColumnType("bit");

                    b.Property<bool>("RestrictByIp")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("OrgID");

                    b.HasIndex("OrgID")
                        .IsUnique();

                    b.ToTable("OrgAttendanceConfigs", (string)null);
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.OrgAttendanceNightDiffExclusion", b =>
                {
                    b.Property<int>("OrgAttendanceNightDiffExclusionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrgAttendanceNightDiffExclusionID"));

                    b.Property<string>("Department")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("OrgAttendanceOvertimePolicyID")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Site")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("OrgAttendanceNightDiffExclusionID");

                    b.HasIndex("OrgAttendanceOvertimePolicyID");

                    b.ToTable("OrgAttendanceNightDiffExclusions", (string)null);
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.OrgAttendanceOvertimeApprovalStep", b =>
                {
                    b.Property<int>("OrgAttendanceOvertimeApprovalStepID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrgAttendanceOvertimeApprovalStepID"));

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("OrgAttendanceOvertimePolicyID")
                        .HasColumnType("int");

                    b.Property<bool>("Required")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("OrgAttendanceOvertimeApprovalStepID");

                    b.HasIndex("OrgAttendanceOvertimePolicyID", "Order");

                    b.ToTable("OrgAttendanceOvertimeApprovalSteps", (string)null);
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.OrgAttendanceOvertimeBucket", b =>
                {
                    b.Property<int>("OrgAttendanceOvertimeBucketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrgAttendanceOvertimeBucketID"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal?>("MaxHours")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int?>("MinimumBlockMinutes")
                        .HasColumnType("int");

                    b.Property<int>("OrgAttendanceOvertimePolicyID")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThresholdHours")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("OrgAttendanceOvertimeBucketID");

                    b.HasIndex("OrgAttendanceOvertimePolicyID", "Key")
                        .IsUnique();

                    b.ToTable("OrgAttendanceOvertimeBuckets", (string)null);
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.OrgAttendanceOvertimePolicy", b =>
                {
                    b.Property<int>("OrgAttendanceOvertimePolicyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrgAttendanceOvertimePolicyID"));

                    b.Property<bool>("AllowPostFiling")
                        .HasColumnType("bit");

                    b.Property<string>("ApprovalFlowType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("AutoApprove")
                        .HasColumnType("bit");

                    b.Property<string>("Basis")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal?>("DailyThresholdHours")
                        .HasColumnType("decimal(6,2)");

                    b.Property<bool>("EarlyOtAllowed")
                        .HasColumnType("bit");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("FilingMode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LimitMode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("MaxPerDayHours")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("MaxPerWeekHours")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("MicroOtBufferMinutes")
                        .HasColumnType("int");

                    b.Property<int>("MinimumBlockMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("NightDiffEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("NightDiffExcludeBreaks")
                        .HasColumnType("bit");

                    b.Property<int>("NightDiffMinimumMinutes")
                        .HasColumnType("int");

                    b.Property<string>("NightDiffWindowEnd")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("NightDiffWindowStart")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("OrgID")
                        .HasColumnType("int");

                    b.Property<string>("OverrideRole")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("PreApprovalRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireHoursMet")
                        .HasColumnType("bit");

                    b.Property<bool>("RestHolidayOverride")
                        .HasColumnType("bit");

                    b.Property<string>("RoundingDirection")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int>("RoundingMinutes")
                        .HasColumnType("int");

                    b.Property<string>("ScopeMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal?>("WeeklyThresholdHours")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("OrgAttendanceOvertimePolicyID");

                    b.HasIndex("OrgID")
                        .IsUnique();

                    b.ToTable("OrgAttendanceOvertimePolicies", (string)null);
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.OrgAttendanceOvertimeScopeFilter", b =>
                {
                    b.Property<int>("OrgAttendanceOvertimeScopeFilterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrgAttendanceOvertimeScopeFilterID"));

                    b.Property<string>("FilterType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("OrgAttendanceOvertimePolicyID")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("OrgAttendanceOvertimeScopeFilterID");

                    b.HasIndex("OrgAttendanceOvertimePolicyID");

                    b.ToTable("OrgAttendanceOvertimeScopeFilters", (string)null);
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.OrgShiftTemplate", b =>
                {
                    b.Property<int>("OrgShiftTemplateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrgShiftTemplateID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("FixedBreakMinutes")
                        .HasColumnType("int");

                    b.Property<string>("FixedEndTime")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int?>("FixedGraceMinutes")
                        .HasColumnType("int");

                    b.Property<string>("FixedStartTime")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("FlexibleEarliestStart")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("FlexibleLatestEnd")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<decimal?>("FlexibleMaxDailyHours")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("FlexibleRequiredDailyHours")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal?>("OpenRequiredWeeklyHours")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("OrgID")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("OrgShiftTemplateID");

                    b.HasIndex("OrgID", "Code")
                        .IsUnique();

                    b.ToTable("OrgShiftTemplates", (string)null);
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.OrgShiftTemplateBreak", b =>
                {
                    b.Property<int>("OrgShiftTemplateBreakID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrgShiftTemplateBreakID"));

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("OrgShiftTemplateID")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("OrgShiftTemplateBreakID");

                    b.HasIndex("OrgShiftTemplateID");

                    b.ToTable("OrgShiftTemplateBreaks", (string)null);
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.OrgShiftTemplateDayOverride", b =>
                {
                    b.Property<int>("OrgShiftTemplateDayOverrideID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrgShiftTemplateDayOverrideID"));

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("IsOffDay")
                        .HasColumnType("bit");

                    b.Property<int>("OrgShiftTemplateID")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("OrgShiftTemplateDayOverrideID");

                    b.HasIndex("OrgShiftTemplateID");

                    b.ToTable("OrgShiftTemplateDayOverrides", (string)null);
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.OrgShiftTemplateOverrideWindow", b =>
                {
                    b.Property<int>("OrgShiftTemplateOverrideWindowID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrgShiftTemplateOverrideWindowID"));

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("OrgShiftTemplateDayOverrideID")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("OrgShiftTemplateOverrideWindowID");

                    b.HasIndex("OrgShiftTemplateDayOverrideID");

                    b.ToTable("OrgShiftTemplateOverrideWindows", (string)null);
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.OrgShiftTemplateWorkDay", b =>
                {
                    b.Property<int>("OrgShiftTemplateWorkDayID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrgShiftTemplateWorkDayID"));

                    b.Property<string>("DayCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("OrgShiftTemplateID")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("OrgShiftTemplateWorkDayID");

                    b.HasIndex("OrgShiftTemplateID");

                    b.ToTable("OrgShiftTemplateWorkDays", (string)null);
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.OvertimeRequest", b =>
                {
                    b.Property<int>("OTRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OTRequestID"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("EmpID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("OTDate")
                        .HasColumnType("date");

                    b.Property<int>("OrgID")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalHours")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("OTRequestID");

                    b.HasIndex("EmpID");

                    b.HasIndex("OTDate");

                    b.HasIndex("OrgID");

                    b.ToTable("OvertimeRequests", (string)null);
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.ShiftAssignment", b =>
                {
                    b.Property<int>("ShiftAssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftAssignmentID"));

                    b.Property<DateTime>("AssignmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("EmpID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OrgID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("ShiftAssignmentID");

                    b.HasIndex("EmpID");

                    b.HasIndex("OrgID", "AssignmentDate");

                    b.ToTable("ShiftAssignments", (string)null);
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.SignupPending", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("SignupPendings", (string)null);
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.TenantAuditLog", b =>
                {
                    b.Property<int>("TenantAuditLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenantAuditLogID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("EntityID")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Meta")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("OrgID")
                        .HasColumnType("int");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("TenantAuditLogID");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OrgID");

                    b.HasIndex("UserID");

                    b.ToTable("TenantAuditLogs", (string)null);
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.Employee", b =>
                {
                    b.HasOne("Subchron.API.Models.Entities.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.LeaveRequest", b =>
                {
                    b.HasOne("Subchron.API.Models.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmpID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.OrgAttendanceNightDiffExclusion", b =>
                {
                    b.HasOne("Subchron.API.Models.Entities.OrgAttendanceOvertimePolicy", null)
                        .WithMany("NightDiffExclusions")
                        .HasForeignKey("OrgAttendanceOvertimePolicyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.OrgAttendanceOvertimeApprovalStep", b =>
                {
                    b.HasOne("Subchron.API.Models.Entities.OrgAttendanceOvertimePolicy", null)
                        .WithMany("ApprovalSteps")
                        .HasForeignKey("OrgAttendanceOvertimePolicyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.OrgAttendanceOvertimeBucket", b =>
                {
                    b.HasOne("Subchron.API.Models.Entities.OrgAttendanceOvertimePolicy", null)
                        .WithMany("Buckets")
                        .HasForeignKey("OrgAttendanceOvertimePolicyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.OrgAttendanceOvertimeScopeFilter", b =>
                {
                    b.HasOne("Subchron.API.Models.Entities.OrgAttendanceOvertimePolicy", null)
                        .WithMany("ScopeFilters")
                        .HasForeignKey("OrgAttendanceOvertimePolicyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.OrgShiftTemplateBreak", b =>
                {
                    b.HasOne("Subchron.API.Models.Entities.OrgShiftTemplate", null)
                        .WithMany("Breaks")
                        .HasForeignKey("OrgShiftTemplateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.OrgShiftTemplateDayOverride", b =>
                {
                    b.HasOne("Subchron.API.Models.Entities.OrgShiftTemplate", null)
                        .WithMany("DayOverrides")
                        .HasForeignKey("OrgShiftTemplateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.OrgShiftTemplateOverrideWindow", b =>
                {
                    b.HasOne("Subchron.API.Models.Entities.OrgShiftTemplateDayOverride", null)
                        .WithMany("WorkWindows")
                        .HasForeignKey("OrgShiftTemplateDayOverrideID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.OrgShiftTemplateWorkDay", b =>
                {
                    b.HasOne("Subchron.API.Models.Entities.OrgShiftTemplate", null)
                        .WithMany("WorkDays")
                        .HasForeignKey("OrgShiftTemplateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.ShiftAssignment", b =>
                {
                    b.HasOne("Subchron.API.Models.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmpID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.OrgAttendanceOvertimePolicy", b =>
                {
                    b.Navigation("ApprovalSteps");

                    b.Navigation("Buckets");

                    b.Navigation("NightDiffExclusions");

                    b.Navigation("ScopeFilters");
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.OrgShiftTemplate", b =>
                {
                    b.Navigation("Breaks");

                    b.Navigation("DayOverrides");

                    b.Navigation("WorkDays");
                });

            modelBuilder.Entity("Subchron.API.Models.Entities.OrgShiftTemplateDayOverride", b =>
                {
                    b.Navigation("WorkWindows");
                });
#pragma warning restore 612, 618
        }
    }
}
